### PR TITLE
Allow retrieving just the body of the document

### PR DESCRIPTION
**Pull request by RobLoach**
By default, Cheerio will retrieve the whole HTML when calling $.html(). This change allows returning just the body through the passing `{ justBody: true }` into the cheerio options.

May want to just do this by default?

### CODE REVIEW

**Comment by DanielRuf** [comment]
See the failing tests.

**Comment by RobLoach** [comment]
A better approach here might be to pass `target` variable.

**Comment by DanielRuf** [comment]
I'm not sure. What issue does this PR resolve? It looks like it makes things more complicated than needed.

**Comment by RobLoach** [comment]
Yeah, going to just close this.

**Pull request closed without merging**
