### PR TITLE
Fix build, get suite passing, Fix spacer component on Outlook and Windows Mail clients

### PR DESCRIPTION
**Pull request by DylanReile**
#104 I've tested on Litmus and removing the unit fixes the spacer component on Windows clients and doesn't regress others.

### CODE REVIEW

**Comment by DylanReile** [comment]
Anything I can do to help this along?

**Comment by SampsonCrowley** [comment]
seriously is this repo abandoned now?

**Comment by marcandre** [comment]
Hopefully there will be some activity soon...

**Comment by SampsonCrowley** [comment]
@marcandre @DylanReile I reached out to zurb directly and received this response:

Hi Sampson,Thanks for reaching out! We're still using Foundation for Emails internally here. There are no plans for us to continue developing it. We are looking for community members to step up and essentially take it over.

Cheers!

Rafi

  | Rafi from ZURB

On Tue, May 21, 2019 at 04:48 PM, "Sampson Crowley" <*@gmail.com> wrote:

Me and some of my fellow developers have put a LOT of time into implementing foundation for emails in our various projects. Both the FfE repo and the related Inky repo have failed to return ANY response to pull requests, issues or questions on if the repo is abandoned.

Please let us know if you are abandoning Foundation for Emails, so we can remove your code from our apps as necessary

**Comment by marcandre** [comment]
Right, I also contacted kball even though he's no longer there and was hoping to hear back today.

Not too sure what's best at this point, create a new org and move the repos there, or have Zurb provide access to the existing repos.

Note that I'm just trying to help but I am not using `inky` personally or through a client.

**Comment by SampsonCrowley** [comment]
It almost seems like we should pick a maintainer at this point, and just make their fork the new base. the claim from rafi they are "looking for community members" is almost laughable, as there have been plenty of offers here that haven't gotten a response

**Comment by marcandre** [comment]
Propose yourself :-)

**Comment by SampsonCrowley** [comment]
I did, they just got back to me, so at least getting somewhere

**Comment by SampsonCrowley** [comment]
Meeting w/ Zurb CEO tomorrow to discuss

**Comment by DylanReile** [comment]
@SampsonCrowley Any news?

**Comment by SampsonCrowley** [comment]
@DylanReile they just stopped responding completely. Apparently they just don't care enough about the users of this library. I'm tired of zurb being in control of this repo when they refuse to maintain it. I vote we fork it and consider someone else as the new base

**Comment by rafibomb** [comment]
Hi all
On this PR, how is it different than https://github.com/foundation/inky-rb/pull/69/files ?

^ This looks like it is meant to resolve the same issue but with different approaches. Do we still need it? @SampsonCrowley

**Comment by rafibomb** [comment]
I TOTALLY get the frustration. I still use Inky along with you all so I also want to see it live on.

ZURB can no longer maintain this project. It has been moved to a new Foundation organization separate from ZURB. 

I'm pretty sure the Yetinauts, who are maintaining all of Foundation would be open to new contributors. I'll loop Joe Workman in to make a plan to open this up to new people.

**Comment by joeworkman** [comment]
I will get together with @rafibomb next week in order to get our ducks in a row so that we can get a release out.

**Comment by AxelTheGerman** [comment]
@joeworkman any news on this? I have looked around quite some time for something to make writing emails easier. This is the only thing that came up but I don't like investing in projects without any sort of activity and/or responsiveness

**Comment by joeworkman** [comment]
Man, time just flies when you are having fun (in the case of quarantine, not so much fun). I have yet to get an official release of Inky under my belt yet. I will see what I can do to learn what I can this week.

**Comment by marcandre** [comment]
Did you finally get push access?

**Comment by joeworkman** [comment]
I can push to this repo. I am awaiting access to publish to NPM and RubyGems now. 

I am working on getting the dependencies updated. Hopefully by the time that is done, I will have the access.

**Comment by joeworkman** [comment]
Give today's release a shot. https://github.com/foundation/inky/releases/tag/v1.4.1

**Comment by joeworkman** [comment]
I have not pushed it up to npm yet. still waiting on access, should be tomorrow.

**Pull request merged**
